version: '3'

services:
  web:
    container_name: weather-app
    build: .
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - REDIS_HOST=weather-redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - integrity

  redis:
    container_name: weather-redis
    image: "redis:alpine"
    ports:
      - 6379:6379
    networks:
      - integrity

networks:
  integrity:
    external: true


  